version: '3'

services:
  web:
    image: mohan006007/dev-image:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
